# Generated by Django 3.2.18 on 2023-07-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster', verbose_name='Заставка'),
        ),
    ]
